export const data = [
  {
    id: "1",
    name: "Classic Blue Denim Jacket",
    category: "Jackets",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "79.99",
    description:
      "A timeless blue denim jacket crafted from premium cotton denim. Features double chest pockets, button cuffs, and a relaxed fit perfect for layering.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue"],
    material: "100% Cotton Denim",
    stock: 120,
    sku: "DENIM001",
  },
  {
    id: "2",
    name: "Elegant Black Evening Dress",
    category: "Dresses",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "149.99",
    description:
      "An elegant black evening dress made of silk blend fabric. Features a fitted waist, subtle V-neckline, and a flowing floor-length skirt ideal for formal events.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black"],
    material: "Silk Blend",
    stock: 60,
    sku: "DRESS002",
  },
  {
    id: "3",
    name: "Casual White Cotton T-Shirt",
    category: "T-Shirts",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "19.99",
    description:
      "A casual white T-shirt made from soft, breathable cotton. Perfect for everyday wear, featuring a classic crew neck and short sleeves.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    material: "100% Cotton",
    stock: 250,
    sku: "TSHIRT003",
  },
  {
    id: "4",
    name: "Slim Fit Chino Pants",
    category: "Pants",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "49.99",
    description:
      "Slim fit chino pants made of durable cotton twill fabric. Features slanted side pockets and a zip fly with button closure.",
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Beige", "Navy", "Olive"],
    material: "98% Cotton, 2% Elastane",
    stock: 150,
    sku: "PANTS004",
  },
  {
    id: "5",
    name: "Cozy Winter Wool Sweater",
    category: "Sweaters",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "89.99",
    description:
      "A cozy wool sweater perfect for winter. Features ribbed cuffs, hem, and neckline, and a comfortable relaxed fit.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Charcoal", "Cream"],
    material: "80% Wool, 20% Nylon",
    stock: 90,
    sku: "SWEATER005",
  },
  {
    id: "6",
    name: "Floral Print Midi Skirt",
    category: "Skirts",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "39.99",
    description:
      "A breezy midi skirt featuring beautiful floral prints and an elastic waistband for comfort.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Pink Floral", "Blue Floral"],
    material: "100% Viscose",
    stock: 110,
    sku: "SKIRT006",
  },
  {
    id: "7",
    name: "Leather Crossbody Bag",
    category: "Accessories",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "129.99",
    description:
      "A stylish leather crossbody bag with adjustable strap and multiple compartments for daily essentials.",
    sizes: [],
    colors: ["Brown", "Black"],
    material: "Genuine Leather",
    stock: 45,
    sku: "BAG007",
  },
  {
    id: "8",
    name: "Graphic Crew Neck Sweatshirt",
    category: "Sweaters",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "54.99",
    description:
      "A comfortable crew neck sweatshirt featuring an eye-catching graphic. Made from soft, pre-shrunk cotton blend.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Red"],
    material: "80% Cotton, 20% Polyester",
    stock: 130,
    sku: "SWEAT008",
  },
  {
    id: "9",
    name: "Slim Fit Black Jeans",
    category: "Pants",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "69.99",
    description:
      "Classic slim fit black jeans with five-pocket styling and a zip fly. Ideal for casual or smart casual looks.",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Black"],
    material: "99% Cotton, 1% Elastane",
    stock: 140,
    sku: "JEANS009",
  },
  {
    id: "10",
    name: "Striped Long Sleeve Shirt",
    category: "T-Shirts",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "29.99",
    description:
      "Long sleeve shirt with classic horizontal stripes. Made with breathable cotton fabric, perfect for layering or standalone wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue/White", "Red/White"],
    material: "100% Cotton",
    stock: 160,
    sku: "TSHIRT010",
  },
  {
    id: "11",
    name: "Men's Waterproof Raincoat",
    category: "Jackets",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "99.99",
    description:
      "Waterproof raincoat with adjustable hood and zip closures. Lightweight yet durable, ideal for rainy days.",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Yellow", "Navy"],
    material: "Polyester",
    stock: 75,
    sku: "JACKET011",
  },
  {
    id: "12",
    name: "Pleated Black Maxi Skirt",
    category: "Skirts",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "44.99",
    description:
      "Elegant black maxi skirt featuring soft pleats and an elastic waistband. Perfect for both casual and formal occasions.",
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    material: "Polyester Blend",
    stock: 95,
    sku: "SKIRT012",
  },
  {
    id: "13",
    name: "Men's Casual Polo Shirt",
    category: "T-Shirts",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "34.99",
    description:
      "Classic polo shirt with a two-button placket and ribbed collar. Soft cotton blend fabric for comfort.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Navy", "Grey"],
    material: "95% Cotton, 5% Elastane",
    stock: 175,
    sku: "POLO013",
  },
  {
    id: "14",
    name: "Women’s Faux Leather Leggings",
    category: "Pants",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "59.99",
    description:
      "Stylish faux leather leggings with high elasticity for a snug fit. Perfect for casual outings or nights out.",
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    material: "Polyurethane and Nylon Blend",
    stock: 80,
    sku: "LEGGING014",
  },
  {
    id: "15",
    name: "Chunky Knit Winter Scarf",
    category: "Accessories",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "24.99",
    description:
      "Warm chunky knit scarf made from soft acrylic fibers. Available in multiple colors to match your winter wardrobe.",
    sizes: [],
    colors: ["Grey", "Red", "Navy"],
    material: "100% Acrylic",
    stock: 200,
    sku: "SCARF015",
  },
  {
    id: "16",
    name: "Men’s Classic White Dress Shirt",
    category: "Shirts",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "45.99",
    description:
      "Button-up dress shirt in crisp white cotton. Perfect for formal or business casual wear.",
    sizes: ["15", "15.5", "16", "16.5", "17"],
    colors: ["White"],
    material: "100% Cotton",
    stock: 140,
    sku: "SHIRT016",
  },
  {
    id: "17",
    name: "Red Hooded Fleece Jacket",
    category: "Jackets",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "69.99",
    description:
      "Soft fleece jacket with zipper closure and a warm hood. Perfect for chilly days and outdoor activities.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red"],
    material: "100% Polyester Fleece",
    stock: 110,
    sku: "JACKET017",
  },
  {
    id: "18",
    name: "Striped Summer Tank Top",
    category: "T-Shirts",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "14.99",
    description:
      "Lightweight striped tank top made with breathable cotton fabric, perfect for hot summer days.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue/White", "Green/White"],
    material: "100% Cotton",
    stock: 190,
    sku: "TANK018",
  },
  {
    id: "19",
    name: "High-Waisted Denim Shorts",
    category: "Pants",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "34.99",
    description:
      "Classic high-waisted denim shorts with frayed edges and five-pocket styling.",
    sizes: ["26", "28", "30", "32"],
    colors: ["Light Blue"],
    material: "100% Cotton Denim",
    stock: 130,
    sku: "SHORTS019",
  },
  {
    id: "20",
    name: "Women’s Soft Knit Cardigan",
    category: "Sweaters",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "54.99",
    description:
      "Soft knit cardigan with button closure and relaxed fit. Perfect layering piece for any season.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "Light Grey", "Dusty Pink"],
    material: "70% Acrylic, 30% Wool",
    stock: 140,
    sku: "CARDIGAN020",
  },
  {
    id: "21",
    name: "Women's Satin Slip Dress",
    category: "Dresses",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "99.99",
    description:
      "Sleek satin slip dress with adjustable spaghetti straps and side slit. Ideal for elegant evening wear.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Champagne", "Black"],
    material: "100% Satin Polyester",
    stock: 70,
    sku: "DRESS021",
  },
  {
    id: "22",
    name: "Men’s Thermal Long Underwear",
    category: "Underwear",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "29.99",
    description:
      "Thermal long underwear providing ultimate warmth and comfort. Made from soft, moisture-wicking fabric.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black"],
    material: "60% Cotton, 40% Polyester",
    stock: 90,
    sku: "UNDERWEAR022",
  },
  {
    id: "23",
    name: "Classic Leather Belt",
    category: "Accessories",
    images: ["/img1.jpg", "/img2.jpg"],
    price: "39.99",
    description:
      "Genuine leather belt with metal buckle. Suitable for formal and casual wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
    material: "Genuine Leather",
    stock: 160,
    sku: "BELT023",
  },
  {
    id: "24",
    name: "Men’s Casual Hoodie",
    category: "Sweaters",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "49.99",
    description:
      "Comfortable casual hoodie with kangaroo pocket and adjustable drawstring hood.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Grey", "Black"],
    material: "80% Cotton, 20% Polyester",
    stock: 180,
    sku: "HOODIE024",
  },
  {
    id: "25",
    name: "Women’s Wrap Around Blouse",
    category: "Shirts",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "44.99",
    description:
      "Stylish wrap-around blouse with tie waist and relaxed fit. Breathable fabric for everyday wear.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Coral"],
    material: "100% Viscose",
    stock: 105,
    sku: "BLOUSE025",
  },
  {
    id: "26",
    name: "Men’s Running Shorts",
    category: "Pants",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "24.99",
    description:
      "Lightweight breathable running shorts with mesh lining and elastic waistband.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Blue", "Red"],
    material: "100% Polyester",
    stock: 140,
    sku: "SHORTS026",
  },
  {
    id: "27",
    name: "Women’s Denim Shirt Dress",
    category: "Dresses",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "69.99",
    description:
      "Casual denim shirt dress with button front and rolled sleeves. Versatile and comfortable.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Blue"],
    material: "100% Cotton Denim",
    stock: 85,
    sku: "DRESS027",
  },
  {
    id: "28",
    name: "Leather Ankle Boots",
    category: "Shoes",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "139.99",
    description:
      "Elegant leather ankle boots with side zipper and stacked heel, perfect for year-round wear.",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Black", "Brown"],
    material: "Genuine Leather",
    stock: 55,
    sku: "SHOES028",
  },
  {
    id: "29",
    name: "Men’s Classic Henley Shirt",
    category: "Shirts",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "29.99",
    description:
      "Classic Henley shirt with three-button placket, soft cotton fabric, and casual fit.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Grey", "White"],
    material: "100% Cotton",
    stock: 150,
    sku: "HENLEY029",
  },
  {
    id: "30",
    name: "Casual Slip-On Sneakers",
    category: "Shoes",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "59.99",
    description:
      "Lightweight casual slip-on sneakers made with breathable mesh fabric and rubber sole.",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["White", "Grey", "Black"],
    material: "Mesh Fabric and Rubber",
    stock: 120,
    sku: "SHOES030",
  },
  {
    id: "31",
    name: "Women's Cotton Wrap Skirt",
    category: "Skirts",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "39.99",
    description:
      "Breathable cotton wrap skirt with tie closure and classic A-line fit.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Red", "Navy"],
    material: "100% Cotton",
    stock: 100,
    sku: "SKIRT031",
  },
  {
    id: "32",
    name: "Men’s Quilted Vest",
    category: "Jackets",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "59.99",
    description:
      "Lightweight quilted vest with zip closure and side pockets, perfect for layering.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive", "Black"],
    material: "Polyester",
    stock: 80,
    sku: "VEST032",
  },
  {
    id: "33",
    name: "Women's Lightweight Blazer",
    category: "Jackets",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "89.99",
    description:
      "Tailored lightweight blazer with a single button closure, perfect for office or events.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black"],
    material: "Polyester Blend",
    stock: 75,
    sku: "BLAZER033",
  },
  {
    id: "34",
    name: "Faux Fur Winter Coat",
    category: "Jackets",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "199.99",
    description:
      "Luxurious faux fur coat with full-length sleeves, perfect for cold winters and stylish evenings.",
    sizes: ["S", "M", "L"],
    colors: ["Cream", "Brown"],
    material: "Faux Fur",
    stock: 40,
    sku: "COAT034",
  },
  {
    id: "35",
    name: "Men’s Casual Canvas Backpack",
    category: "Accessories",
    images: [
      "/img1.jpg",
      "/img2.jpg",
    ],
    price: "79.99",
    description:
      "Durable canvas backpack with multiple compartments and padded shoulder straps. Great for daily use.",
    sizes: [],
    colors: ["Tan", "Grey"],
    material: "Canvas",
    stock: 85,
    sku: "BACKPACK035",
  },
];
